# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #DEE6DB
background         #141619
cursor             #DEE6DB

active_tab_foreground     #141619
active_tab_background     #DEE6DB
inactive_tab_foreground   #DEE6DB
inactive_tab_background   #141619

active_border_color   #DEE6DB
inactive_border_color #141619
bell_border_color     #07111A

color0      #3B3D40
color1		#07111A
color2		#0F1920
color3		#394641
color4		#2B4C4B
color5		#5C6C5C
color6		#788A72
color7		#C7D3C3
color8		#8B9489
color9		#0A1723
color10		#13212A
color11		#4B5E56
color12		#396564
color13		#7A907B
color14		#A0B898
color15		#C7D3C3
