#
# weechat -- buffer_autoset.conf
#
# WARNING: It is NOT recommended to edit this file by hand,
# especially if WeeChat is running.
#
# Use /set or similar command to change settings in WeeChat.
#
# For more info, see: https://weechat.org/doc/quickstart
#

[look]
instant = on
timer = 1

[buffer]
core.chanmon.title = ""
core.highmon.title = ""
core.weechat.notify = "3"
exec.exec.conky.short_name = "conky"
exec.exec.conky.title = ""
exec.exec.translated_dict.short_name = ""
exec.exec.weather.short_name = ""
irc.freenode.##news.highlight_words_del = "$nick"
irc.freenode.##news.localvar_set_my_control = "1"
irc.freenode.##news.short_name = "news"
irc.server.*.notify = "3"
