#
# weechat -- sec.conf
#
# WARNING: It is NOT recommended to edit this file by hand,
# especially if WeeChat is running.
#
# Use /set or similar command to change settings in WeeChat.
#
# For more info, see: https://weechat.org/doc/quickstart
#

[crypt]
cipher = aes256
hash_algo = sha256
passphrase_file = ""
salt = on

[data]
__passphrase__ = on
freenode_password = "D6D1578425318156B49632D3C24134735C31E382C77EA2087D8EA48412CACCD0BF69FD2CCD3DA7E7693B5470639B974E4EC466"
