apt = [
    "apt-file",
    "build-essential",
    "coreutils",
    "curl",
    "eza",
    "findutils",
    "git",
    "gnome-shell-extension-manager",
    "neovim",
    "ripgrep",
    "uuid-runtime",
    "windsurf",
    "zoxide",
    "zsh",
]
cargo = [
    "metapac",
    "pacdef",
]
rustup = ["stable-x86_64-unknown-linux-gnu"]
snap = [
    "bare",
    "chezmoi",
    "core",
    "core18",
    "core20",
    "core22",
    "desktop-security-center",
    "firefox",
    "firmware-updater",
    "gh",
    "gimp",
    "gnome-3-38-2004",
    "gnome-42-2204",
    "gtk-common-themes",
    "gtk2-common-themes",
    "keybase",
    "prompting-client",
    "snap-store",
    "snapd",
    "snapd-desktop-integration",
]

