# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(141619)
$foreground = rgb(DEE6DB)
$color0 = rgb(3B3D40)
$color1 = rgb(07111A)
$color2 = rgb(0F1920)
$color3 = rgb(394641)
$color4 = rgb(2B4C4B)
$color5 = rgb(5C6C5C)
$color6 = rgb(788A72)
$color7 = rgb(C7D3C3)
$color8 = rgb(8B9489)
$color9 = rgb(0A1723)
$color10 = rgb(13212A)
$color11 = rgb(4B5E56)
$color12 = rgb(396564)
$color13 = rgb(7A907B)
$color14 = rgb(A0B898)
$color15 = rgb(C7D3C3)
